# Generated by Django 4.1.7 on 2023-03-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='text',
            field=models.TextField(default='Nedokoncana objava'),
        ),
    ]
